# Implement BackPropagation for Regression Problem Using Keras

### Import Libraries

In [10]:
import numpy as np
import pandas as pd

### Creating a Data Frame

In [11]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], 
                  columns=['cgpa', 'profile_score', 'lpa'])

In [12]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

### Creating ANN Model for Regression

In [13]:
#pip install tensorflow

In [14]:
import tensorflow 
from tensorflow import keras 
from keras import Sequential 
from keras.layers import Dense, Input

### Creating Neural Network

In [15]:
model = Sequential()
model.add(Input(shape=(2,)))  # Specify the input shape using an Input layer
model.add(Dense(2, activation="linear")) 
model.add(Dense(1, activation="linear"))

In [16]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.get_weights()

[array([[ 0.32732248,  0.8874985 ],
        [-1.1457528 , -1.1358426 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.1895492],
        [-1.1080663]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
### updating keras calculated weight with weight calculated in 
# hard code code in previous screen for comaprsion only 

In [19]:
new_weights = [
    np.array([[0.1, 0.1], [0.1, 0.11]], dtype=np.float32),  # Weights for layer 1
    np.array([0, 0], dtype=np.float32),                    # Biases for layer 1
    np.array([[0.1], [0.1]], dtype=np.float32),            # Weights for layer 2
    np.array([0.], dtype=np.float32)                       # Biases for layer 2
]


In [20]:
Optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss = 'mean_squared_error',optimizer=Optimizer)

### Model Training 

In [21]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs = 75,verbose =1 ,batch_size = 1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 135.0732  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 134.8731
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 187.5459 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 128.9728 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 128.6457
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 110.2560
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 134.5811 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 150.4987 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 90.3161  
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 122.4874 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 93.5118 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 98.7216 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99.0518 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 90.7368 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75.8156 
Epoch 16/75

### Weights Return by Keras

In [28]:
model.get_weights()

[array([[ 0.51491076,  1.0754621 ],
        [-0.9669001 , -0.9566292 ]], dtype=float32),
 array([0.18446343, 0.18483369], dtype=float32),
 array([[-1.0224715 ],
        [-0.95906603]], dtype=float32),
 array([-0.19142848], dtype=float32)]